
  Pod::Spec.new do |s|
    s.name = 'CordovaPlugins'
    s.version = '4.4.0'
    s.summary = 'Autogenerated spec'
    s.license = 'Unknown'
    s.homepage = 'https://example.com'
    s.authors = { 'Capacitor Generator' => 'hi@example.com' }
    s.source = { :git => 'https://github.com/ionic-team/does-not-exist.git', :tag => '4.4.0' }
    s.source_files = 'sources/**/*.{swift,h,m,c,cc,mm,cpp}'
    s.ios.deployment_target  = '13.0'
    s.xcconfig = {'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) COCOAPODS=1 WK_WEB_VIEW_ONLY=1' }
    s.dependency 'CapacitorCordova'
    s.swift_version  = '5.1'
    s.dependency 'Firebase/Messaging', '~> 7.4.0'
    s.vendored_frameworks = 'sources/CordovaPluginFirebase/src/ios/Crashlytics/Crashlytics.framework', 'sources/CordovaPluginFirebase/src/ios/Crashlytics/Fabric.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/GoogleAppMeasurement.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/MeasurementNanoPB.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/FirebaseCore.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/FirebaseAnalytics.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/GoogleUtilities.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/nanopb.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/FirebaseInstanceID.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Analytics/FirebaseCoreDiagnostics.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Auth/GTMSessionFetcher.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Auth/FirebaseAuth.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Messaging/FirebaseMessaging.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Performance/GoogleToolboxForMac.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/Performance/FirebasePerformance.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/RemoteConfig/Protobuf.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/RemoteConfig/FirebaseRemoteConfig.framework', 'sources/CordovaPluginFirebase/src/ios/Firebase/RemoteConfig/FirebaseABTesting.framework'
    s.exclude_files = 'sources/**/*.framework/Headers/*.h'
  end