export let routes = {
  tab: {
    mainPage:(id?: string | number) => id?  `/tab/MainPage/${id}` : `/tab/MainPage`,
    pickPhoto: "/tab/PickPhoto",
    notices: "/tab/Notices",
    profile: (id: string | number) => `/tab/Profile/${id}`,
    login: "/tab/Login",
    adminPanel: "/tab/AdminPanel",
  },
  menu: {
    accountSetting: `/AccountSetting`,
    noticeSetting: "/NoticeSetUp",
    passwordChange: "/PasswordChange",
    invoice: (id: string | number) => `/Invoice/${id}`,
    signUp: "/SignUp",
  },
  storages: "/Storages",
  trade: "/Trade",
  blacklist: "/Blacklist",
  chatroomPage: "/ChatroomPage",
  chatroom: (id: string | number) => `/chatroom/${id}`,
  post: (id: string | number) => `/post/${id}`,
  payment: "/Payment",
  package: "/Package",
  mainNotice: "/mainNotice",
};
