name: fake-flow

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_DB: toystory
  POSTGRES_USER: toystory
  POSTGRES_PASSWORD: toystory
  SERVER_HOST: 34.194.183.36
  SERVER_USER: ubuntu
  SERVER_DIR: /home/ubuntu/toystory

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh files
        run: |
          cd
          mkdir -p .ssh
          cd .ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > id_rsa
          chmod 400 id_rsa
          ssh-keyscan ${{env.SERVER_HOST}} >> known_hosts
          echo "" >> config
          echo "Host toystory" >> config
          echo "  Hostname ${{env.SERVER_HOST}}" >> config
          echo "  User ${{env.SERVER_USER}}" >> config
          pwd
          find
      - name: check ssh connection
        run: |
          ssh toystory "docker ps"
      - name: archive ssh setup
        uses: actions/upload-artifact@v3
        with:
          name: .ssh
          path: ~/.ssh
  deploy-docker:
    needs:
      - setup-ssh
    runs-on: ubuntu-latest
    steps:
      - name: restore ssh setup
        uses: actions/download-artifact@v3
        with:
          name: .ssh
          path: ssh-tmp
      - name: check ssh connection
        run: |
          mv ssh-tmp ~/.ssh
          cd ~/.ssh
          chmod 400 id_rsa
          ssh server whoami
      - name: restore docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-files
      - name: check docker image
        run: |
          file fake.img
          file docker-compose.yml
      - name: upload docker files
        run: |
          rsync -SavLPz fake.img server:${{env.SERVER_DIR}}
          ssh server "docker load < ${{env.SERVER_DIR}}/fake.img"
          rsync -SavLPz docker-compose.yml server:${{env.SERVER_DIR}}
          ssh server "cd ${{env.SERVER_DIR}} && cat docker-compose.yml"
